// Generated by CoffeeScript 1.12.7

/*
	Custom
	Last update: 2018/04/30

	Author:	Taigo Ito
	Site: https://qwel.design
	Twitter: @taigoito
	Location: Tokyo
 */
var Fader, FaderCustom, MyEvent, Scrolling, Slidebar, Slidemenu, Util,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

if (!(typeof history.pushState === "function")) {
  $('body').append('<p class="no-support">このWebページは現在ご利用のブラウザをサポートしていません。<br>最新のブラウザをインストールして再度ご来訪ください。</p>');
}

if ('ontouchend' in document && $(window).width() < 1024) {
  MyEvent = {
    isSupportTouch: true,
    touch: 'touchend',
    start: 'touchstart',
    move: 'touchmove',
    end: 'touchend',
    points: {
      x: 0,
      y: 0
    },
    isDragging: false
  };
} else {
  MyEvent = {
    isSupportTouch: false,
    touch: 'click',
    start: 'mousedown',
    move: 'mousemove',
    end: 'mouseup mouseout',
    points: {
      x: 0,
      y: 0
    },
    isDragging: false
  };
}

if ('onwheel' in document) {
  MyEvent.wheel = 'wheel';
} else {
  MyEvent.wheel = 'mousewheel';
}

Util = {
  transitionEnd: function($el) {
    var callback, dfd;
    dfd = new $.Deferred;
    callback = function() {
      dfd.resolve($el);
    };
    if (($el != null) && $el.length && ($el.css('transition') != null)) {
      $el.on('transitionend', callback);
      dfd.done(function() {
        $el.off('transitionend', callback);
      });
    } else {
      dfd.resolve();
    }
    return dfd;
  },
  animationEnd: function($el) {
    var callback, dfd;
    dfd = new $.Deferred;
    callback = function() {
      dfd.resolve($el);
    };
    if (($el != null) && $el.length && ($el.css('animation') != null)) {
      $el.on('animationend', callback);
      dfd.done(function() {
        $el.off('animationend', callback);
      });
    } else {
      dfd.resolve();
    }
    return dfd;
  }
};

$(document).on(MyEvent.touch, '[data-history="back"]', function() {
  history.back();
  return false;
});


/*
	Scrolling
	Last update: 2017/10/15
 */

Scrolling = (function() {
  function Scrolling(options) {
    var ref, targetSelector;
    if (options == null) {
      options = {};
    }
    this.$el = (ref = options.$el) != null ? ref : $(document);
    targetSelector = location.hash;
    if (this.$el && targetSelector) {
      this.scroll(targetSelector);
    }
    this.handleEvents();
  }

  Scrolling.prototype.handleEvents = function() {
    if (this.$el) {
      this.$el.on(MyEvent.touch, '[data-location="scroll"]', (function(_this) {
        return function(el) {
          var $target, targetSelector;
          $target = $(el.currentTarget);
          targetSelector = $target.data('target');
          _this.scroll(targetSelector);
          return false;
        };
      })(this));
    }
  };

  Scrolling.prototype.scroll = function(targetSelector) {
    var dfd, targetTop;
    dfd = new $.Deferred;
    targetTop = $(targetSelector).offset().top;
    targetTop -= $(window).height() * 0.05;
    $('html, body').animate({
      scrollTop: targetTop
    }, 1000, 'swing', function() {
      return dfd.resolve();
    });
    return dfd;
  };

  return Scrolling;

})();


/*
	Slidebar
	Last update: 2017/10/15
 */

Slidebar = (function(superClass) {
  extend(Slidebar, superClass);

  function Slidebar(options) {
    var data, ref, ref1, ref2, ref3, ref4, ref5, ref6, ref7, ref8, ref9, selector;
    if (options == null) {
      options = {};
    }
    this.windowScrollHandler = bind(this.windowScrollHandler, this);
    options.$el || (options.$el = false);
    this.$targetEl = (ref = options.$targetEl) != null ? ref : $('main + aside[role="complementary"]');
    this.$template = (ref1 = options.$template) != null ? ref1 : $('#slidebar-template');
    data = (ref2 = options.data) != null ? ref2 : {};
    options.selector || (options.selector = {});
    selector = {
      abs: (ref3 = options.selector.abs) != null ? ref3 : '#slidebar-open-abs',
      fixed: (ref4 = options.selector.fixed) != null ? ref4 : '#slidebar-open-fixed',
      overlay: (ref5 = options.selector.overlay) != null ? ref5 : '#slidebar-overlay',
      bar: (ref6 = options.selector.bar) != null ? ref6 : '#slidebar',
      menu: (ref7 = options.selector.menu) != null ? ref7 : '#slidemenu',
      close: (ref8 = options.selector.close) != null ? ref8 : '#slidebar-close'
    };
    this.render(data);
    this.$abs = this.$targetEl.find(selector.abs);
    this.$fixed = this.$targetEl.find(selector.fixed);
    this.$overlay = this.$targetEl.find(selector.overlay);
    this.$bar = this.$targetEl.find(selector.bar);
    this.$menu = this.$targetEl.find(selector.menu);
    this.$close = this.$targetEl.find(selector.close);
    this.showBarHeight = (ref9 = options.showBarHeight) != null ? ref9 : false;
    if (this.showBarHeight) {
      this.isScrolled = false;
    } else {
      this.$fixed.addClass('show');
      this.showBarHeight = 0;
      this.isScrolled = true;
    }
    this.isShown = false;
    Slidebar.__super__.constructor.call(this, options);
  }

  Slidebar.prototype.render = function(data) {
    var compiled, output;
    compiled = _.template(this.$template.html());
    output = compiled({
      data: data
    });
    return this.$targetEl.append(output);
  };

  Slidebar.prototype.handleEvents = function() {
    $('[data-toggle="slidebar"]').on(MyEvent.touch, (function(_this) {
      return function() {
        if (_this.isShown) {
          _this.hideBar();
        } else {
          _this.showBar();
        }
        return false;
      };
    })(this));
    $(window).on('scroll', this.windowScrollHandler);
    Slidebar.__super__.handleEvents.call(this);
  };

  Slidebar.prototype.showBar = function() {
    var dfd1, dfd2;
    dfd1 = new $.Deferred();
    dfd2 = new $.Deferred();
    this.isShown = true;
    if (this.isScrolled) {
      dfd1 = Util.transitionEnd(this.$fixed.removeClass('show'));
    } else {
      dfd1.resolve();
    }
    dfd1.done((function(_this) {
      return function() {
        Util.transitionEnd(_this.$bar.addClass('show')).then(function() {
          _this.$overlay.addClass('show');
          _this.$close.addClass('show');
          Util.transitionEnd(_this.$menu.addClass('show')).then(function() {
            dfd2.resolve();
          });
        });
      };
    })(this));
    return dfd2;
  };

  Slidebar.prototype.hideBar = function() {
    var dfd1, dfd2;
    dfd1 = new $.Deferred();
    dfd2 = new $.Deferred();
    this.isShown = false;
    this.$overlay.removeClass('show');
    this.$close.removeClass('show');
    Util.transitionEnd(this.$menu.removeClass('show')).then((function(_this) {
      return function() {
        Util.transitionEnd(_this.$bar.removeClass('show')).then(function() {
          dfd1.resolve();
        });
      };
    })(this));
    dfd1.done((function(_this) {
      return function() {
        if (_this.isScrolled) {
          _this.$fixed.addClass('show');
        }
        dfd2.resolve();
      };
    })(this));
    return dfd2;
  };

  Slidebar.prototype.windowScrollHandler = function() {
    var h;
    h = $(window).height() * this.showBarHeight;
    if (this.isShown) {
      this.hideBar();
    } else {
      if ($(window).scrollTop() > h && !this.isScrolled) {
        this.isScrolled = true;
        this.$fixed.addClass('show');
      } else if ($(window).scrollTop() < h && this.isScrolled) {
        this.isScrolled = false;
        this.$fixed.removeClass('show');
      }
    }
  };

  return Slidebar;

})(Scrolling);


/*
	Slidemenu
	Last update: 2017/10/15
 */

Slidemenu = (function(superClass) {
  extend(Slidemenu, superClass);

  function Slidemenu(options) {
    var $nav, listItems, ref;
    if (options == null) {
      options = {};
    }
    options.$el || (options.$el = $(document));
    $nav = (ref = options.$nav) != null ? ref : $('nav');
    listItems = [];
    $nav.find('ul').each(function(i, ul) {
      listItems[i] = [];
      $(ul).find('li').each(function(j, li) {
        var $a, $li;
        $a = $(li).find('a').clone();
        $li = $('<li>').append($a);
        listItems[i][j] = {
          html: $li.html()
        };
      });
    });
    options.data || (options.data = listItems);
    Slidemenu.__super__.constructor.call(this, options);
    return;
  }

  Slidemenu.prototype.scroll = function(targetId) {
    var dfd;
    dfd = new $.Deferred();
    if (this.isShown) {
      dfd = this.hideBar();
    } else {
      dfd.resolve();
    }
    return dfd.done(function() {
      return Slidemenu.__super__.scroll.call(this, targetId);
    });
  };

  return Slidemenu;

})(Slidebar);


/*
	Fader
	Last update: 2017/11/28
 */

Fader = (function() {
  function Fader(options) {
    var ref, ref1, ref2, ref3, ref4, ref5, ref6, ref7;
    if (options == null) {
      options = {};
    }
    this.$fader = (ref = options.$fader) != null ? ref : $('.fader');
    this.$items = $('.fader-item').detach();
    this.$toggle = (ref1 = options.$prev) != null ? ref1 : $('.fader-toggle');
    this.$prev = (ref2 = options.$prev) != null ? ref2 : $('.fader-prev');
    this.$next = (ref3 = options.$next) != null ? ref3 : $('.fader-next');
    this.hasCounter = (ref4 = options.hasCounter) != null ? ref4 : false;
    this.interval = (ref5 = options.interval) != null ? ref5 : 5000;
    this.activeIndex = 0;
    this.len = this.$items.length;
    if (this.hasCounter) {
      this.$counterCurrent = (ref6 = options.counterCurrent) != null ? ref6 : $('.fader-counter-current');
      this.$counterMax = (ref7 = options.counterMax) != null ? ref7 : $('.fader-counter-max');
      this.$counterCurrent.text(this.activeIndex + 1);
      this.$counterMax.text(this.len);
    }
    this.isPlay = false;
    if (this.interval && this.len > 1) {
      this.isPlay = true;
    }
    this.$currentItem = $(this.$items[this.activeIndex]);
    this.$fader.append(this.$currentItem);
    setTimeout((function(_this) {
      return function() {
        if (_this.isPlay) {
          return _this.move(1);
        }
      };
    })(this), this.interval);
    this.handleEvents();
  }

  Fader.prototype.handleEvents = function() {
    $(document).on(MyEvent.touch, '[data-toggle="fader"]', (function(_this) {
      return function() {
        if (_this.interval) {
          _this.toggleMode();
        }
        return false;
      };
    })(this)).on(MyEvent.touch, '[data-fade="prev"]', (function(_this) {
      return function() {
        _this.move(-1);
        return false;
      };
    })(this)).on(MyEvent.touch, '[data-fade="next"]', (function(_this) {
      return function() {
        _this.move(1);
        return false;
      };
    })(this));
  };

  Fader.prototype.toggleMode = function() {
    if (this.isPlay) {
      this.isPlay = false;
    } else {
      this.isPlay = true;
      setTimeout((function(_this) {
        return function() {
          if (_this.isPlay) {
            return _this.move(1);
          }
        };
      })(this), this.interval);
    }
  };

  Fader.prototype.move = function(direction) {
    var $nextItem;
    this.activeIndex += this.len + direction;
    this.activeIndex = this.activeIndex % this.len;
    $nextItem = $(this.$items[this.activeIndex]);
    this.$fader.append($nextItem);
    if (this.hasCounter) {
      this.$counterCurrent.html(this.activeIndex + 1);
    }
    Util.animationEnd($nextItem.addClass('enter')).done((function(_this) {
      return function() {
        return $nextItem.removeClass('enter');
      };
    })(this));
    Util.animationEnd(this.$currentItem.addClass('leave')).done((function(_this) {
      return function() {
        _this.$currentItem.removeClass('leave');
        _this.$currentItem.remove();
        _this.$currentItem = $nextItem;
        return setTimeout(function() {
          if (_this.isPlay) {
            return _this.move(1);
          }
        }, _this.interval);
      };
    })(this));
  };

  return Fader;

})();


/*
	Fader-Custom
	Last update: 2018/09/28
 */

FaderCustom = (function(superClass) {
  extend(FaderCustom, superClass);

  function FaderCustom(options) {
    var $container, $description, $fader, $img, $imgs, $item, $txt, $txts, i, k, l, len, len1;
    if (options == null) {
      options = {};
    }
    $container = $('.fader-custom');
    $description = $('.fader-description');
    $imgs = $container.find('img').detach();
    $txts = $container.find('p').detach();
    $fader = $('<ul>').addClass('fader').addClass('fader-figures').addClass('list-unstyled').addClass('mb-3');
    $container.empty().append($fader);
    for (i = k = 0, len = $imgs.length; k < len; i = ++k) {
      $img = $imgs[i];
      $item = $('<li>').addClass('fader-item').addClass('fader-top').attr('style', 'background-image:url(' + $img.src + ')');
      $fader.append($item);
    }
    for (i = l = 0, len1 = $txts.length; l < len1; i = ++l) {
      $txt = $txts[i];
      $description.append($txt);
    }
    FaderCustom.__super__.constructor.call(this, options);
  }

  return FaderCustom;

})(Fader);
